elasticDb:
  image: dockerfile/elasticsearch
  expose:
    - "9200"
    - "9300"
web:
  build: web
  ports:
    - "3000:3000"
  links:
    - elasticDb
  environment:
    DB_HOST: "http://elasticDb:9200"
    INDEX_NAME: "subman7"
    IS_DEBUG: "false"
parser:
  build: parser
  links:
    - elasticDb
  environment:
    DB_HOST: "http://elasticDb:9200"
    INDEX_NAME: "subman7"
    IS_DEBUG: "false"
